Proyectos/TiendaMercado/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articulos 
  
  #ruta para el localhost:3000
  root 'articulos#index' 
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Proyectos/TiendaMercado/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Proyectos/TiendaMercado/app/models/articulo.rb
class Articulo < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates_processing_of :image
  validate :image_size_validation

 
private
  def image_size_validation
    errors[:image] << "should be less than 1 MB" if image.size > 1.0.megabytes
  end
end

Proyectos/TiendaMercado/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Proyectos/TiendaMercado/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Proyectos/TiendaMercado/app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :authenticate_user!,except:[:index, :show]
  before_action :set_articulo, only: [:show, :update, :destroy]
  # GET /articulos
  # GET /articulos.json
  def index
    
  @q = params[:q]
  if @q
    @articulos = Articulo.where("titulo like ?", "%#@q%")
  else
    #Articulo.all
    @articulos = Articulo.all
   end
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
    #Contador Visitas + 1
    @articulo = Articulo.where('id = ?', params[:id]).first
    @articulo.update_column('count_vts', @articulo.count_vts + 1) if @articulo.present?
    
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)
    @articulo.count_vts = -1
    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo was successfully created.' }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1
  # PATCH/PUT /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: 'Articulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url, notice: 'Articulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articulo_params
      params.require(:articulo).permit(:titulo, :cuerpo, :link_mercado, :count_vts, :image)
    end
end

Proyectos/TiendaMercado/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

Proyectos/TiendaMercado/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

Proyectos/TiendaMercado/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

Proyectos/TiendaMercado/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

Proyectos/TiendaMercado/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

Proyectos/TiendaMercado/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

Proyectos/TiendaMercado/app/helpers/application_helper.rb
module ApplicationHelper
end

Proyectos/TiendaMercado/app/helpers/articulos_helper.rb
module ArticulosHelper
end

Proyectos/TiendaMercado/app/helpers/pets_helper.rb
module PetsHelper
end

Proyectos/TiendaMercado/app/views/articulos/_form.html.erb
<%= form_for @articulo, html: { multipart: true } do |f| %>
  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>
      <ul>
      <% @articulo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field_titulo">
    <%= f.label :titulo %>
    <%= f.text_field :titulo %>
  </div>

  <div class="field_cuerpo">
    <%= f.label :cuerpo %>
    <%= f.text_area :cuerpo %>
  </div>

  <div class="field_link">
    <%= f.label :link_mercado %>
    <%= f.text_area :link_mercado %>
  </div>

  <div class="field_imagen">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %> 
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Proyectos/TiendaMercado/app/views/articulos/edit.html.erb
<h1>Editing Articulo</h1>

<%= render 'form', articulo: @articulo %>
<%= link_to 'Show', @articulo %> |
<%= link_to 'Back', articulos_path %>

Proyectos/TiendaMercado/app/views/articulos/index.html.erb
<% @articulos.each do |articulo| %>
<p id="notice"><%= notice %></p>
<% end %>
<h1>Articulos</h1>
<% @articulos.each do |articulo| %>
<div class="row">
	<div class="art_main2">
		<div class="img_index"><%= link_to (image_tag articulo.image_url(:thumb).to_s),articulo %></div>
	</div>
		<div class="ttl_index"><%= link_to articulo.titulo,articulo %></div>	
</div>
       
 <!--        
 	<div class="cp_index"><%= link_to articulo.cuerpo,articulo %></div>
 	<div class=="link"><%= articulo.link_mercado %></div>
        <div class=="titulo"><%= articulo.count_vts %></div> -->
        
 <!--       <div<%= link_to 'Show', articulo %></div>
        <div><%= link_to 'Edit', edit_articulo_path(articulo) %></div>
        <div><%= link_to 'Destroy', articulo, method: :delete, data: { confirm: 'Are you sure?' } %></tddiv -->
<% end %> 
    
<br>

<!-- 
<%= link_to 'New Articulo', new_articulo_path %> 
 -->

Proyectos/TiendaMercado/app/views/articulos/new.html.erb
<h1>New Articulo</h1>

<%= render 'form', articulo: @articulo %>

<%= link_to 'Back', articulos_path %>

Proyectos/TiendaMercado/app/views/articulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @articulo.titulo %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @articulo.cuerpo %>
</p>

<p>
  <strong>Link mercado:</strong>
  <%= @articulo.link_mercado %>
</p>
<!-- 
<p>
  <strong>Count vts:</strong>
  <%= @articulo.count_vts %>
</p>
-->
<p>
  <strong>Image:</strong>
  <%= image_tag @articulo.image.thumb.url %>
</p>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_articulo_path(@articulo) %> |
<%= link_to 'Back', articulos_path %>
<%end%>

Proyectos/TiendaMercado/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TiendaMercado</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container" id="main-container">
  	
  	<%= render "/partials/navigationTop"%>
  	<%= render "/partials/busquedaArticulos"%>
  	<p class=""><%= notice %></p>
    <p class=""><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

Proyectos/TiendaMercado/app/views/partials/_busquedaArticulos.erb
		<form>
  			<div class="col-lg-7">
		    	<div class="input-group">
		      	<span class="input-group-btn">
		      		<input class="form-control" name="q" <%= @q %> >
					<button class="btn btn-default"  type="submit">Buscar</button>
		      	</span>
		    	</div>
		 	</div>
		 </form>

Proyectos/TiendaMercado/app/views/partials/_navigationTop.html.erb
  	<header>
  		
  		<div class="image_logo">
  					<%= image_tag "imgWall", width: '100%'%>
  		</div>
  		<nav class="be-blue white">
  			<ul class="no-list row center-xs">
  				<li class="col-md">
  					<%= link_to 'Inicio', articulos_path %>
  				</li>
  				<% if user_signed_in? %>
  				<li class="col-md">
  					<%= link_to 'Nuevo Articulo', new_articulo_path%>
  				</li>
  				<%end%>
  				<li class="col-md">
  					<%= link_to "Programacion"%>
  				</li>
  				<li class="col-md">
  					<%= link_to "Tecnologia"%>
  				</li>

	  				<% if user_signed_in? %>
  				<li class="col-md">
  					<%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete%>
  				</li>
  				<%else%>
  				<li class="col-md">
  					<%= link_to "Iniciar sesion", new_user_session_path%>
  				</li>
  				<li class="col-md">
  					<%= link_to "Crear sesion", new_user_registration_path%>
  				</li> 
				<%end%>
  			</ul>
  		</nav>
  	</header>

Proyectos/TiendaMercado/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>